server:
  port: 8083
spring:
#  静态资源映射
  mvc:
    static-path-pattern: /storage/fetch/**
  resources:
    static-locations: file:F:\Documents\Works@cskaoyan\07 Project2\storage
  http:
    multipart:
      enabled=true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123456
mybatis:
  type-handlers-package: com.cskaoyan.typehandler
pagehelper:
  helper-dialect: mysql
#springboot默认日志级别是info
logging:
  level:
    com.cskaoyan.mapper: debug
    com.cskaoyan.service: warn
storage:
  path: F:\Documents\Works@cskaoyan\07 Project2\storage